# Site wide configuration

title: 聂微东，一枚Web技术领域的手艺人
locale: zh_CN
description: 博观而约取,厚积而薄发...


logo: site-logo.png
search: true
url:
comments: true

# Jekyll configuration

#permalink:   /:categories/:title/
permalink:   /:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: nieweidong
  avatar: me.jpg
  email: darrencode@qq.com
  disqus-shortname: nieweidong
  twitter: nieweidong
  facebook: weidong.nie
  github: nieweidong
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: nieweidong
  flickr: #username
  tumblr: #username
  pinterest: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
